using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FluxMapper.SourceGenerator;

/// <summary>
/// An <see cref="IIncrementalGenerator"/>
/// that turns <c>[MapFrom(typeof(TSource))] public partial class TDestination</c> into a real,
/// zero-reflection, zero-<c>Expression.Compile()</c> static factory method on that same partial class --
/// the one execution tier in this project that can honestly report <c>ExecutionEligibility.AotSafe = true</c>
///, because everything it produces is ordinary compiled C# the
/// destination assembly ships with, not code assembled at runtime.
///
/// Scope, stated plainly rather than silently: this generator does its OWN flat, direct-assignment-only
/// member matching (exact name, identity/implicit conversion) -- it does NOT yet share
/// <see cref="Building.MappingPlanBuilder"/>'s pipeline (naming conventions, flattening, nested/collection
/// mapping, nullability policy, resolvers, ReverseMap, ...). Making a Roslyn-symbol-driven twin of that
/// pipeline that produces the exact same <c>MappingPlan</c> IR the reflection-based builder produces --
/// so Explain()/AssertConfigurationIsValid() and generated code are guaranteed to agree -- is real,
/// substantial follow-up work (the "future compile-time input" the IR's own doc comments anticipate),
/// not something this pass claims to have finished. What's here is genuinely generated, genuinely
/// compiled, and genuinely verified end-to-end for the flat case.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class MapFromGenerator : IIncrementalGenerator
{
    private const string MapFromAttributeFullName = "FluxMapper.Abstractions.MapFromAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            MapFromAttributeFullName,
            predicate: static (node, _) => node is ClassDeclarationSyntax c && c.Modifiers.Any(SyntaxKind.PartialKeyword),
            transform: static (ctx, _) => Analyze(ctx));

        context.RegisterSourceOutput(targets.Where(static m => m is not null), static (spc, model) => Execute(spc, model!));
    }

    private static MapFromModel? Analyze(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol destinationSymbol) return null;
        if (destinationSymbol.ContainingType is not null) return null; // scope: top-level (namespace-nested) classes only, see type doc comment.

        var attribute = ctx.Attributes.FirstOrDefault();
        if (attribute is null || attribute.ConstructorArguments.Length != 1) return null;
        if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol sourceSymbol) return null;

        var members = new List<MapFromMember>();
        var destinationProps = destinationSymbol.GetMembers().OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && !p.IsIndexer && p.SetMethod is { DeclaredAccessibility: Accessibility.Public });
        var sourceProps = sourceSymbol.GetMembers().OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && !p.IsIndexer && p.GetMethod is { DeclaredAccessibility: Accessibility.Public })
            .ToDictionary(p => p.Name, p => p);

        foreach (var destProp in destinationProps)
        {
            if (!sourceProps.TryGetValue(destProp.Name, out var sourceProp)) continue;

            var conversion = ctx.SemanticModel.Compilation.ClassifyConversion(sourceProp.Type, destProp.Type);
            if (!conversion.Exists) continue;
            if (!(SymbolEqualityComparer.Default.Equals(sourceProp.Type, destProp.Type) || conversion.IsImplicit)) continue;

            members.Add(new MapFromMember(destProp.Name, NeedsCast: !SymbolEqualityComparer.Default.Equals(sourceProp.Type, destProp.Type), destProp.Type.ToDisplayString()));
        }

        var namespaceName = destinationSymbol.ContainingNamespace.IsGlobalNamespace ? null : destinationSymbol.ContainingNamespace.ToDisplayString();

        return new MapFromModel(
            DestinationName: destinationSymbol.Name,
            DestinationFullName: destinationSymbol.ToDisplayString(),
            SourceFullName: sourceSymbol.ToDisplayString(),
            Namespace: namespaceName,
            IsRecord: destinationSymbol.IsRecord,
            Members: ImmutableArray.CreateRange(members));
    }

    private static void Execute(SourceProductionContext spc, MapFromModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by FluxMapper.SourceGenerator from [MapFrom] -- zero reflection, zero Expression.Compile().");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var indent = "";
        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var keyword = model.IsRecord ? "partial record" : "partial class";
        sb.AppendLine($"{indent}public {keyword} {model.DestinationName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    /// <summary>Generated by FluxMapper.SourceGenerator from [MapFrom(typeof({model.SourceFullName}))]. AOT-safe: no reflection, no Expression.Compile().</summary>");
        sb.AppendLine($"{indent}    public static {model.DestinationFullName} MapFrom({model.SourceFullName} source)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        global::System.ArgumentNullException.ThrowIfNull(source);");
        sb.AppendLine($"{indent}        return new {model.DestinationFullName}");
        sb.AppendLine($"{indent}        {{");
        foreach (var member in model.Members)
        {
            var valueExpr = member.NeedsCast ? $"({member.DestinationTypeDisplay})source.{member.Name}" : $"source.{member.Name}";
            sb.AppendLine($"{indent}            {member.Name} = {valueExpr},");
        }
        sb.AppendLine($"{indent}        }};");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");

        spc.AddSource($"{model.DestinationName}.MapFrom.g.cs", sb.ToString());
    }

    private sealed record MapFromModel(
        string DestinationName,
        string DestinationFullName,
        string SourceFullName,
        string? Namespace,
        bool IsRecord,
        ImmutableArray<MapFromMember> Members);

    private sealed record MapFromMember(string Name, bool NeedsCast, string DestinationTypeDisplay);
}
